project:
  type: website

website:
  title: "James Brock's academic homepage"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: projects.qmd
        text: Projects
      - href: publications.qmd
        text: Publications
      - href: events.qmd
        text: Events
      - href: blog.qmd
        text: Blog
  sidebar:
    style: "docked"
    logo: "./images/prof_pic.jpeg"
    search: true
    collapse-level: 2
    contents:
      - icon: github
        text: Github
        url: https://github.com/IntelligentSystemsLaboratory
      - icon: envelope
        text: "Email"
        url: mailto:james.brock@bristol.ac.uk
      - text: "Google Scholar"
        url: https://scholar.google.com/citations?user=<google-scholar-user>
      - text: Pro-AI CDT
        url: https://www.bristol.ac.uk/cdt/practice-oriented-ai/
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



